### ISSUE TITLE
panic with ErrorsByField

### ISSUE THREAD

**Issue by newhook** [asaskevich/govalidator#112]
This is with go 1.5.

```
package main

import (
    "fmt"

    "github.com/asaskevich/govalidator"
)

type Foo struct {
    Name string `valid:"required"`
    Type string `valid:"required"`
}
type Bar struct {
    F Foo `valid:"required"`
}

func main() {
    f := Bar{Foo{Type: "Foo"}}
    result, err := govalidator.ValidateStruct(f)
    if err != nil {
        errors := govalidator.ErrorsByField(err)
        fmt.Println(errors)
    }
    println(result)

}
```

```
➜  val  go run main.go
panic: interface conversion: error is govalidator.Errors, not govalidator.Error

goroutine 1 [running]:
github.com/asaskevich/govalidator.ErrorsByField(0x708598, 0xc8201a3960, 0xc8201a3800)
    /Users/matthew/go/src/github.com/asaskevich/govalidator/validator.go:883 +0x22b
main.main()
    /Users/matthew/tmp/val/main.go:21 +0xf0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

**Comment by F21** [comment]
Seeing the same issue here. @waltton: Are you planning to submit your patch as a PR>

**Comment by asaskevich** [comment]
Does this issue appear currently?
